apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
    - port: 5672
      targetPort: 5672
      name: amqp
      nodePort: 30672
    - port: 15672
      targetPort: 15672
      name: http
      nodePort: 31672
  type: NodePort
