apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-volume
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /volumes/rabbitmq
    type: DirectoryOrCreate
